apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-dns
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgBj2SDXKuTkoiYISglqVMB2ppfsaEZMBLDscEqe9za86Zxfi5X1u2OZxaN90+gAfWyh4Olz2LzkqGHnibf7K5f40drxJDcHtH091OcR2+3r8BscCY7gLcC4u3gv9tCCXq71PBRV8gaandi8DC/6XnrIvpcycQLHTqs+/IyzXV6aTC0StDRjhSAVQN1fd2917G4BuX84QiUyW3ewt5nTkT4L32xBGamqI0z82xZPccx4bjAK0q0GkbnwF+ttM4BlfuI4kWWwslyymRSz6UoHftYd0lurh9B89NCL/u1t8Q3lg+/zWASmh5UcL80Bazza/3kXsfamxZlQ8qddqm6MBqw4tGcRE9XUZGyWggu68ti0/3D7U7jUPgWM1m7XBtPEGWELLw0NAdbb4sAzefdfFc5UIZdyamGruulJ9z+RJvLmRPMCf+bjrPAFizsg/pcNKhJIe9UZ6PsaIDNJ9p5co4upn9wfxQjHEG3Bm0ZytdHvoJaocNe2n2h+gnRD0dDxtbS48zMILcE9/UTuzJ3hB5jJ78xvoOGEpkMz5ywTZCWUOLwU1NGA0b+Wr70GqSTeUnErRzMeH9M8eZ8+nhkarIJIivfg/Ts+EceHFmiagvypvE66Ln1MnxiYng77fzq1dcp3vqa2VlKDd9SWD1+wx/ck3asumce3NgSfMtht31nGommDwQvr48UhZcwVkd99A4/lsk/quFFg42yfVApwsVF4pjJVLv9WTHj5PqybemA4gYMH4bAR

