---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 5.0.1
  values:
    alertmanager:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
        - alertmanager.dev.dexlab.tk
        tls:
        - secretName: dev-dexlab-tk-tls
          hosts:
          - alertmanager.dev.dexlab.tk
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: thin-disk
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 2Gi
    grafana:
      serviceMonitor:
        selfMonitor: true
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
        - grafana.dev.dexlab.tk
        tls:
        - secretName: dev-dexlab-tk-tls
          hosts:
          - grafana.dev.dexlab.tk
      persistence:
        enabled: true
        storageClassName: thin-disk
        accessModes:
        - ReadWriteOnce
        size: 2Gi
    kubeEtcd:
      serviceMonitor:
        scheme: https
        insecureSkipVerify: true
    prometheus:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
        - prometheus.dev.dexlab.tk
        tls:
        - secretName: dev-dexlab-tk-tls
          hosts:
          - prometheus.dev.dexlab.tk
      prometheusSpec:
        retention: 1d
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: thin-disk
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 4Gi
            selector: {}
        additionalScrapeConfigs:
        - job_name: 'metallb-system'
          kubernetes_sd_configs:
          - role: pod
          relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: keep
            regex: (.*metallb.*)
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
        - job_name: 'unknown'
          kubernetes_sd_configs:
          - role: pod
          relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: drop
            regex: (.*metallb.*)
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
