---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: flux
  chart:
    repository: https://weaveworks.github.io/flux/
    name: flux
    version: 0.9.2
  values:
    image:
      repository: docker.io/weaveworks/flux
      tag: 1.12.1
    helmOperator:
      create: true
      createCRD: false
      chartsSyncInterval: "1m"
    git:
      url: "git@github.com:krzyzan/dexlab-flux"
      branch: "minikube"
      path: "common,minikube"
      label: "flux-sync-minikube"
      pollInterval: "1m"
    registry:
      excludeImage: "*metallb*"
    additionalArgs:
    - --sync-garbage-collection
