apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: krzysztof.t.krzyzanowski@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    dns01:
      providers:
      - name: cf-dns
        cloudflare:
          email: krzysztof.t.krzyzanowski@gmail.com
          apiKeySecretRef:
            name: cloudflare-dns
            key: api-key
