apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-dns
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgBGZ8NdZg7H4PhL0ZW4Ll9SN2wW9qOxkBtTZcsoeyytS262FP/rcu5TAYA7H4n/e0wHKXv3B4QkOR8o8Y3LKfVAEFEcGKdptXyATghS4d/mlZDWj1q1MNnOKNrFffuvJBEjPDXnhf2eDGAUALmYU0w4fmY5zocMrnO5w22mvEL/ttwdpBn1/i/Vbu3qnVTVJ17wlyS6DzOwL4Ts4wqe4eD4OBcReDgTgOCJoQ3FCCiWKAayFC8i2sIjLlpJBKov+qy7zl2pIOlHVpd2riR/EdhTUkGlawbSipr36S6idjSvd5VVlulH1Ym2/iyz6iRughSFvfgaATVCJY/LaUQvN659ByHg5bxf2rKfShx0isJbPgufGMAFUcFqoXUAT4gGGWZCW36kCjEZevFv8JCYe9mpjFLusvLKIkLP7gEnEG3rOLXM5nHWjWKp3PivY4veuk2oz64MOKjJjdPFsIfmkdGpi1os04yHv1h0j9w2vdCGT4Sw7EdDR2KZ84ES4rsnclKKxNgS0j2bcZuEXRkCz5v5g2pbUgFjp35mapjvJH2j0NilnSkNn68FHHkHYxesyLQN71mhml0K/HA1uZ3bNToRz5e5proiF0xH5jok5NQOFoAnMyugaHss6dSKpHxmO7H6oVBtjRigaASBjTBIzAa3JWY38kcjMXvlIUV5PIhR5j4T+JHLEjjEKDWl09ALozKJtSEWChprEaYgHiT/RwqzYyVsJ8ouW+y2fLa9Tw4c1pY3niHa

