apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-dns
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgBHuNpjxbEfCo6k1I5AYRHTTPs4tNYzNx17so2U7XQPmtdP+YT+d9zopYLZilrc5F2B+KYlqlKcUWAw9uXZCKe8qBFXkOFaKHF9oFzwKUtTKZUZhPzeRplkQuMGgRVoyXa0edZmRnijQj2b/5JKf+tFkzfTY9c1WsDNfVPB3II3b+loOg4CmANcYwY7r3VaaJcZ/ylDUokA/Ux4aDXwaY6tTz0ixrebg1jmEkL6PlAy/XwMMZJ+jIwFSC+3RyqhYIYk/6wZko5IvU5ove29dgoXx8j3dr3ZCF5CUbF6cdycZX8k4OrpH6J0w7JEr3IkWnjEyvCdTEsx+MNtjy46rMyy/0RRADPOTcK7n/fibV7XXN+aoIu/O6y33b96OdiPI8bPviKlPjDLu3mn2Se8FjQY7Qreb98G3vbGnzYsTxneL5Lu+gs8gY94fdYFuVXDJ6iaV77GKr0+LThwkqO3QB2WNDymUfkdXfjkj9Sw9az0C2PAM4MV7Q76/STuEU36fSfjeiDYnjC+G9VCo/FHJe+ZRUcERWyrn/2QCkN+fCii0oKe1Zm8imq4TRFZmnfr9XOiPSQzcYsAG5y7bO5xU/Y4FEC14yIqSTudmszTj9tOx/LaEg2qzHCHFWW1/7BVEu/AxtRFVzHncPx5YdN5HOjcdZKxuI+1xJ5oFukpPEBGyjMtFZ0OnRBSuSpqOcX/+oGHEJRd8nG7oJbT2yK4QBgyfRopbK1zgEgQyygP2P9T1htE3jOJ

