apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: wildcard-dev-dexlab-tk
  namespace: nginx-ingress
spec:
  secretName: dev-dexlab-tk-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: '*.dev.dexlab.tk'
  dnsNames:
  - dev.dexlab.tk
  acme:
    config:
    - dns01:
        provider: cf-dns
      domains:
      - dev.dexlab.tk
      - '*.dev.dexlab.tk'
