apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: wildcard-stg-dexlab-tk
  namespace: nginx-ingress
spec:
  secretName: stg-dexlab-tk-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: '*.stg.dexlab.tk'
  dnsNames:
  - stg.dexlab.tk
  acme:
    config:
    - dns01:
        provider: cf-dns
      domains:
      - stg.dexlab.tk
      - '*.stg.dexlab.tk'
