---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: nginx-ingress
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nginx-ingress
    version: 1.4.0
  values:
    controller:
      stats:
        enabled: true
      metrics:
        enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: prometheus-operator
