apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: wildcard-prd-dexlab-tk
  namespace: nginx-ingress
spec:
  secretName: prd-dexlab-tk-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: '*.prd.dexlab.tk'
  dnsNames:
  - prd.dexlab.tk
  acme:
    config:
    - dns01:
        provider: cf-dns
      domains:
      - prd.dexlab.tk
      - '*.prd.dexlab.tk'
