apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-dns
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgDLqaNKv+HdCSGbUiOytWCX2VFI072GlCfh43OkFJV2sxA7tOjo66n1Og6uPzP2hawksrg6/bmkPXkQiMLkLFhSm2sJwuu1nj4NxibPXfYuH3VTfn7Ufi2QakfX70xG5qJhhMhuEtBsPbrQWyD2crfOvQ/M9oc2kjdpo1mEU51ZDj44k2WvjdKQW1nhaWXVAwiwSVutJYOOQczlCV7o+CbowsCcbCp6Ve025HRB+OA3bReeU4b93/DVZIkxvlGTm69R3+QFzVzHCumjVASRENwtOXxsnwrgojsg+keiHs/n2qs1UZC3H0LJfP/ewRUcHq+WTHTuv4ECJqeWkiODfYvIZsfjOVasHGQXbT7xAc2aWEk0wOOS4Ac/cqw88upTCSUmZG2lzCpBuMTKhy493GjY50UZuYdz0K3RY63xzTnxKlOSBNg+M0/pewtK82MjUDmuFkUjSKXI9sQfBCDsShZ5+QDEEPZhlAXjYB26tysQDiJc+cyI0rRPUfdnTwHVJjWiecCmXbcj+VECSMYAcC71d0w8SRQlKWC3OW9sTkLbmOmP9FyoVzFO7oYAFkmmCvAdOXz7QwEcI2hrcYd8ZLzJEuyRpT1bzlsEhZmEOR8VxrQb2Kv1YsWVedtQN3d0zOsZDkCzn8b4JYkFh03VZ6VcTUimLHUrBf/XWpD28CG0xERo4DMOpKLjz9QTMdgt1kYidTVn+I7H/5iw50YziBh+ba4tSTfgUuFUYxlc4fIgGWhSpyDZ

